name: Push On Docker And Run Pipeline
on:
  push:
    branches:
      - main
jobs:
  docker-build-push:  
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: harbor login
        run: docker login  devendra.harbor.com:31000 -u user-github-runner -p GGwuhagegEgKDsT6vCDlR8Aj35LAfh3f
      - name: Docker Build 
        run: |
          docker build -t devendra.harbor.com:31000/inventyv/myimage:latest .

      - name: Push Image On Harbor
        run: |
          docker push devendra.harbor.com:31000/inventyv/myimage:latest           

      - name: Google Cloud Authentication
        uses: google-github-actions/auth@v0.4.0
        with:
             credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - name: Publish Message 
        uses: miraliumre/actions-pubsub@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          topic_name: ${{ secrets.TOPIC_NAME }}
          message: '{"run":"pipeline"}'
      
