name: Push On Docker And Run Pipeline
on:
  push:
    branches:
      - main
jobs:
  docker-build-push:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker Build 
        run: |
          docker build -t devendra110203/myimage:latest Dockerfile

      - name: Push Image On Docker Hub
        run: |
          docker push devendra110203/myimage:latest           